name: Check End-of-Line Sequences
run-name: Check End-of-Line Sequences

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: Specifies the commitish to checkout. Defaults to $GITHUB_SHA. For more information, see <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows>.
        required: false
        type: string
      default-eol:
        default: lf
        description: Specifies the default end-of-line sequence. The supported values are "lf"(default), "crlf", and "mixed".
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  check-eol:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Check End-of-Line Sequences
        env:
          DEFAULT_EOL: ${{ inputs.default-eol }}
        run: |
          exit_code=0

          while IFS= read line; do
            if [[ $line =~ ^i/([^ ]*)\ +w/[^\ ]*\ +attr/[^$'\t']+$'\t'(.+)$ ]] ; then
              index_eol=${BASH_REMATCH[1]}
              if [ "$index_eol" != $DEFAULT_EOL ] ; then
                echo "${BASH_REMATCH[2]}:"$'\t'"End-of-line sequence in index($index_eol) must be LF."
                exit_code=1
              fi
            else
              echo 'Unable to match '"$line"
              exit_code=1
            fi
          done < <(git ls-files --eol)

          exit $exit_code
