name: Check End-of-Line Sequences
run-name: Check End-of-Line Sequences

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: Specifies the commitish to checkout. Defaults to $GITHUB_SHA. For more information, see <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows>.
        required: false
        type: string
      default-eol:
        default: lf
        description: Specifies the default end-of-line sequence. The supported values are "lf"(default), "crlf", and "mixed".
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  check-eol:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Check End-of-Line Sequences
        uses: Arthri/check-eol-composite@v1
        with:
          default-eol: ${{ inputs.default-eol }}
